version: "3"

services:
  influxdb:
    image: influxdb:latest
    env_file:
      - stack.env
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:latest
    env_file:
      - stack.env
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

volumes:
  grafana-storage:
  influxdb-storage:
